# Decision Tree's

Decision tree's are a supervised algorith used for both regression and classification.

### Pros:
- Simple to understand and interpret. the tree can be visualized and decisions leading to specific outcomes can be tracked
- Require little preprocessing compared to other procedures. They can even handle blank data or missing values. (This is not true for the [scikit-learn](http://scikit-learn.org/stable/modules/tree.html) implementation).
- Compute is expensive: logarithmic in terms of the data used to train the model.
- Good for both numerical and categorical data.

### Cons:
- Prone to overfitting, especially for deep tree's.
- Not always robust. they are susceptible to small fluctuations in the data. this is remedied using ensemble methods (random forest).
- Only captures linear combinations of features.
- NP-Complete: This is a greedy algorithm that optimizes each node individiaually so there is no assurance that the minima obtained is close to global optimum.
- Can create biased trees if the data is imbalanced --> it is important to balance your training data. 

### How they work:

1.) Recursively parittions the data using a selected feeature and threshold with the objective that data with the same label are on the same branch of the tree.

2.) For a given partition (feature _j_, threshold _tm_) calculate the impurity (i.e. the proportion of objects from class _k_ that fall in class _m_).

3.) Find and chose the partition that minimizes this impurity.

4.) Repeat the procedure with new branches till the tree depth is reached.

### Classification criteria

If a target classification outcome is given by the proportion of objects from class _k_ that are classified as being in class _m_, we have:

<img src="ml_doc_images/impurity.png" width="250px"/>

Then the following are commonly used criteria for classification

- Gini index: 

<img src="ml_doc_images/Gini.png" width="250px"/>

- Cross entropy

<img src="ml_doc_images/CrossEntropy.png" width="250px"/>

- Mis-classification

<img src="ml_doc_images/Misclass.png" width="220px"/>

### Regression criteria

For continuos variables, for mode _m_ with _N_ measurments a common way to determine locations for future split si trying to minimise either L1 or L2 norm using the mean values at terminal nodes

- L2 norm

<img src="ml_doc_images/L2.png" width="250px"/>

- L1 norm

<img src="ml_doc_images/L1.png" width="250px"/>



# Examples copied from scikit-learn page

### Classification (in sklearn)

As with other classifiers, DecisionTreeClassifier takes as input two arrays: an array X, sparse or dense, of size [n_samples, n_features] holding the training samples, and an array Y of integer values, size [n_samples], holding the class labels for the training samples:

```python
>>> from sklearn import tree
>>> X = [[0, 0], [1, 1]]
>>> Y = [0, 1]
>>> clf = tree.DecisionTreeClassifier()
>>> clf = clf.fit(X, Y)
```
After being fitted, the model can then be used to predict the class of samples:

``` python
>>> clf.predict([[2., 2.]])
array([1])
```
Alternatively, the probability of each class can be predicted:

```python
>>> clf.predict_proba([[2., 2.]])
array([[ 0.,  1.]])
```
DecisionTreeClassifier is capable of both binary (where the labels are [-1, 1]) classification and multiclass (where the labels are [0, …, K-1]) classification.

Using the Iris dataset, we can construct a tree as follows:

```python
>>> from sklearn.datasets import load_iris
>>> from sklearn import tree
>>> iris = load_iris()
>>> clf = tree.DecisionTreeClassifier()
>>> clf = clf.fit(iris.data, iris.target)
```
Once trained, we can export the tree in Graphviz format using the export_graphviz exporter.

Below is an example graphviz export of the above tree trained on the entire iris dataset; the results are saved in an output file iris.pdf:

```python
>>> import graphviz 
>>> dot_data = tree.export_graphviz(clf, out_file=None) 
>>> graph = graphviz.Source(dot_data) 
>>> graph.render("iris") 
```

Jupyter notebooks also render these plots inline automatically:

```python
>>> dot_data = tree.export_graphviz(clf, out_file=None, 
                         feature_names=iris.feature_names,  
                         class_names=iris.target_names,  
                         filled=True, rounded=True,  
                         special_characters=True)  
>>> graph = graphviz.Source(dot_data)  
>>> graph 
```

### Regression

Decision trees can also be applied to regression problems, using the DecisionTreeRegressor class.

As in the classification setting, the fit method will take as argument arrays X and y, only that in this case y is expected to have floating point values instead of integer values:

```python
>>> from sklearn import tree
>>> X = [[0, 0], [2, 2]]
>>> y = [0.5, 2.5]
>>> clf = tree.DecisionTreeRegressor()
>>> clf = clf.fit(X, y)
>>> clf.predict([[1, 1]])
array([ 0.5])
```

# Random Forest

A random forest is an ensemble method that tries to fit dataset using multiple decision trees trained on a subset of the data, and use the average result to improve accuracy and reduce effects of over-fitting. The sub-sample size is always the same as the original input sample size but the samples are drawn with replacement if bootstrap=True (default).



```python
class sklearn.ensemble.RandomForestClassifier(n_estimators=10, criterion=’gini’, max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=’auto’, max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=1, random_state=None, verbose=0, warm_start=False, class_weight=None)
```

# Gradient boosted Trees and AdaBoost

Gradient boosted trees use a series of weak (shallow) trees/learnes where the output of one tree is the input of the subsequent tree, and they are used to fit on the residuals.

The advantages of GBRT are:

- Natural handling of data of mixed type (= heterogeneous features)
- Predictive power
- Robustness to outliers in output space (via robust loss functions)
The disadvantages of GBRT are:

- Scalability, due to the sequential nature of boosting it can hardly be parallelized.

GradientBoostingClassifier supports both binary and multi-class classification. The following example shows how to fit a gradient boosting classifier with 100 decision stumps as weak learners:
### Classification
```python
>>> from sklearn.datasets import make_hastie_10_2
>>> from sklearn.ensemble import GradientBoostingClassifier

>>> X, y = make_hastie_10_2(random_state=0)
>>> X_train, X_test = X[:2000], X[2000:]
>>> y_train, y_test = y[:2000], y[2000:]

>>> clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
...     max_depth=1, random_state=0).fit(X_train, y_train)
>>> clf.score(X_test, y_test)                 
0.913...
```
### Regression
GradientBoostingRegressor supports a number of different loss functions for regression which can be specified via the argument loss; the default loss function for regression is least squares ('ls').
```python
>>> import numpy as np
>>> from sklearn.metrics import mean_squared_error
>>> from sklearn.datasets import make_friedman1
>>> from sklearn.ensemble import GradientBoostingRegressor

>>> X, y = make_friedman1(n_samples=1200, random_state=0, noise=1.0)
>>> X_train, X_test = X[:200], X[200:]
>>> y_train, y_test = y[:200], y[200:]
>>> est = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1,
...     max_depth=1, random_state=0, loss='ls').fit(X_train, y_train)
>>> mean_squared_error(y_test, est.predict(X_test))    
5.00...
```

### AdaBoost

In the case of AdaBoost, a series of models are trained as in GBT but the weights of the nodes are changed over time according to their discriminative power and the predictions are done with the wieghted average of the trees.
